### ISSUE TITLE
Error from gradle: gmtool command not found. You have to specify the Genymotion path with the genymotion.config.genymotionPath parameter.

### ISSUE THREAD

**Issue by gsusie** [Genymobile/genymotion-gradle-plugin#1]
## unable to use this plugin with my android app. Running Android Studio 1.1.0, Android-Gradle plugin v.1.10, : build.gradle is:

buildscript {
    ext.kotlin_version = '0.10.770'
    ext.junit_version = '4.12'
    ext.rxjava_version = '1.0.7'
    ext.rxandroid_version = '0.24.0'
    ext.retrofit_version = '1.9.0'
    ext.kk_version = '0.1.0-SNAPSHOT'

```
repositories {
    mavenCentral()
    maven { url 'http://oss.sonatype.org/content/repositories/snapshots' }
    maven { url  "http://dl.bintray.com/genymobile/Genymotion" }
}

dependencies {
    classpath 'com.android.tools.build:gradle:1.1.0'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.genymotion:plugin:0.1'
}
```

}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.genymotion.gradleplugin'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

```
defaultConfig {
    applicationId "com.scoir.rxandroidkotlin"
    minSdkVersion 15
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
    androidTest.java.srcDirs += 'src/androidTest/kotlin'
    test.java.srcDirs += 'src/test/kotlin'
}
```

}

repositories {
    mavenCentral()
    maven { url 'http://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "com.jakewharton:kotterknife:$kk_version"

 }

**Comment by eyal-lezmy** [comment]
Hi @nimble 
We are opening the applications for the beta test program this week. You can fill the form to try to access these features soon. Here is the link: http://bit.ly/gm-beta
