### ISSUE TITLE
Delete sdcard directory before running tests

### ISSUE THREAD

**Issue by ScottBishop** [Genymobile/genymotion-gradle-plugin#10]
Hi there, I am using this plugin to run tests on a few build machine. During the tests we are storing images on the sdcard and then copying them to a server. 

The problem we are having is that if a emulator crashes during running our tests, we are not able to delete the images off the device (considering it is not running anymore). Then the next time that emulator is started for tests, there are still images on the sdcard that are unwanted images -- they will skew the test results. 

We want to add a `deleteImages` task that runs after the emulator is started but before tests are run. There doesn't seem like an easy way to do that. Any help would be much appreciated.

**Comment by eyal-lezmy** [comment]
Hi Scott,

First I'm really surprised the emulator crashes sometimes during your tests. I would really appreciate a feedback to the [support team](https://www.genymotion.com/#!/contact) about that, detailing as much as possible when it happens. So we can fix the problem.

Then, to try to help you, you can add this piece of code at the end of your `build.gradle` file:

``` groovy
afterEvaluate {
    tasks.withType(com.genymotion.tasks.GenymotionLaunchTask).each { genymotionTask ->
        genymotionTask.doFirst {
            for(def device in genymotion.getDevices(genymotionTask.flavor)) {
                println "${genymotion.config.genymotionPath}gmtool admin factoryreset $device.name"
                println "${genymotion.config.genymotionPath}gmtool admin factoryreset $device.name".execute().text
            }
        }
    }
}
```

It will simply reset to factory state each device before the launch task.

Thanks a lot for this question, we are thinking about a way to handle this use case directly from the plugin in the future.

**Comment by ScottBishop** [comment]
Great, thank you! I assume this resets the developer options as well. Is there a way to turn off the animations programmatically? Or an alternative, how would I run an Exec task called cleanDeviceAutomationImages just after start up? 

![screen shot 2015-11-19 at 11 36 38 am](https://cloud.githubusercontent.com/assets/1944329/11281975/deb49604-8eb1-11e5-8a8c-d4b384a2b825.png)

**Comment by eyal-lezmy** [comment]
Your very welcome!
We plan to add a way to do manipulated these settings already (throught [the command line](https://www.genymotion.com/#!/developers/gm-tool) and/or our [Java API](https://www.genymotion.com/#!/developers/java-api)). It will for arrive into the gradle plugin then.

I found a very interesting Gist/conversation about this problem [here](https://gist.github.com/xrigau/11284124) I'm sure it will help you to solve this problem.

As you first problem is solved, I close this issue.
Thanks a lot again!

Cheers
