### ISSUE TITLE
Gradle 1.3 Uptake

### ISSUE THREAD

**Issue by traviswestbrook** [Genymobile/genymotion-gradle-plugin#11]
Currently this plugin will break when using the com.android.tools.build:gradle1.3 and above. This is a result of a change in the naming conventions of the test tasks.

Old : connectedAndroidTest{buildVariant}
new : connected{buildVariant}AndroidTest

**Comment by eyal-lezmy** [comment]
Hi Travis, 

Thanks for your feedback. This bug has already been fixed and will be released very soon. 
We will support from 1.0 to latests release. 

We're now testing daily we the last Android plugin release (including beta) so this should not happen again. 

To solve your problem you can read the issue #7 where we proposed a workaround. 

Let us know if it's fine for you. 

Cheers 
Eyal

**Comment by traviswestbrook** [comment]
Awesome thanks!
