### ISSUE TITLE
GMTool command failed. Error code: 6.Failed to log user

### ISSUE THREAD

**Issue by ScottBishop** [Genymobile/genymotion-gradle-plugin#12]
We are getting a bunch of error messages on our build machines that say Wrong Username or Password. It is sporadic and not happens about 50 percent of the time. It causes our build to crash. We add the license, username, and password by adding it in a grade.properties as follows. I have attached a screenshot of the full stacktrace too. We would like to get this fixed asap.

Thanks in advance,

`04-Dec-2015 11:42:26 FAILURE: Build failed with an exception.
04-Dec-2015 11:42:26    
04-Dec-2015 11:42:26    * What went wrong:
04-Dec-2015 11:42:26    A problem occurred configuring project ':main:WorkdayApp'.
04-Dec-2015 11:42:26    > Failed to notify project evaluation listener.
04-Dec-2015 11:42:26       > GMTool command failed. Error code: 6.Failed to log user
04-Dec-2015 11:42:26         Failed to retrieve template list.
04-Dec-2015 11:42:26    
04-Dec-2015 11:42:26` 

![screen shot 2015-12-04 at 11 55 55 am](https://cloud.githubusercontent.com/assets/1944329/11600102/62d77ffe-9a7f-11e5-9a6d-0606494ff155.png)

**Comment by eyal-lezmy** [comment]
Hi Scott,

I would need more information to help you:
- What is the gradle.properties file path you are talking about?
- What is the content of gradle.properties? (replace you credentials by XXX)
- Could you please launch the command adding `genymotion.config.verbose true` to your build.gradle and adding option `--debug` to your gradle task command and paste the end of the result on this thread?

**Comment by eyal-lezmy** [comment]
Up on this issue or I will have to close it.
