### ISSUE TITLE
How do you launch existing emulator instance?

### ISSUE THREAD

**Issue by cooperkong** [Genymobile/genymotion-gradle-plugin#16]
Hi

Maybe I have missed something here, but how can I start an existing instance?

Thanks!
WenChao

**Comment by cooperkong** [comment]
figured out myself

```
devices {
        "Google Nexus 4 - 5.0.0 - API 21 - 768x1280" {
            template "Google Nexus 4 - 5.0.0 - API 21 - 768x1280"
            productFlavors "dev"
        }
    }
```

**Comment by cooperkong** [comment]
Just experienced a weird issue.
If I was using an existing instance and launch it from genymotionLaunch , run the test and finish it using genymotiongFinish, it seems that this instance was removed from the original device list.

**Comment by eyal-lezmy** [comment]
When you start your `connectedAndroidTest` task (or the task you listed on `genymotion.config.launchTask` property), the declared device(s) will be automatically created and started by the Gradle plugin for Genymotion. If the device is already started, nothing will happen, so your tests will be executed on this device. The same way, if the device is already created, it won't be recreated but just started if needed.

After the `connectedAndroidTest` task (or the one in `genymotion.config.launchTask`), another Genymotion task will be executed, this task will stop and delete the declared devices. That's the role of the `genymotionFinish` task. This is to guarantee each one of your tests runs have a clean device instance to avoid side effects between tests.
But you can customise this behaviour if it does not fit your needs. On each devices you can set these properties:
- `stopWhenFinish false` if you want the device to remain started
- `deleteWhenFinish false` if you want the device to stop the device but you don't want it to be deleted

According to your last message, I advise you to not use `genymotionLaunch` and `genymotionFinish` tasks manually. The Genymotion tasks are automatically created and injected into your build. As far as you use the standard Android test tasks or your custom tasks that you reference on `genymotion.config.launchTask`, everything should work correctly without calling the genymotion tasks explicitly.

**Comment by cooperkong** [comment]
Sounds good, will try out this approach.

**Comment by cooperkong** [comment]
`connectedAndroidTest` works fine after set taskLaunch.
One more concern I have, I understand the point to run tests on clean device instance. But I have  installed Google apps on the instance and don't want to lost it after test, it seems that I had to skip genymotionFinish, thus I may need to run gemynotionLaunch manully, any thoughts on this?

**Comment by eyal-lezmy** [comment]
To make it clear you should not control the executed task, just configure correctly the plugin. And everything will be fine :-) 

If you use default connected*AndroidTest tasks from the Android Gradle plugin you can avoid setting genymotion.config.taskLaunch property. The plugin will set everything up for you. If you set the taskLaunch to "connectedAndroidTest" you will loose the multi flavor support. 
genymotion.config.taskLaunch should be used only when you launch your instrumented test with a custom task that the Genymotion Gradle plugin doesn't know. 

I hope this is more clear for you. 

Concerning the custom device including the gapps you can simply avoid deleting the device after the tests by setting the property deleteWhenFinish to false for each custom device you declare on the plugin.

**Comment by cooperkong** [comment]
Thanks for the reply!
I think 'deleteWhenFinish' is what I needed in my case.
