### ISSUE TITLE
always tips error

### ISSUE THREAD

**Issue by chuanY** [Genymobile/genymotion-gradle-plugin#2]
Error:Cause: gmtool command not found. You have to specify the Genymotion path with the genymotion.config.genymotionPath parameter.

but i have define this:
genymotion {
    config {
        genymotionPath = "/Applications/Genymotion.app/Contents/MacOS/"
    }
}

**Comment by eyal-lezmy** [comment]
Hi @chuanY,
This plugin is still on closed beta. You need a specific Genymotion version to use it. You will be able to use it when we will release `gmtool` a command line tool for Genymotion.

**Comment by chuanY** [comment]
Hi @eyal-lezmy 
Thanks for your replay, and what's time the gmtool will be released

**Comment by eyal-lezmy** [comment]
Hi @chuanY
We are opening the applications for the beta test program this week. You can fill the form to try to access these features soon. Here is the link: http://bit.ly/gm-beta

**Comment by chuanY** [comment]
@eyal-lezmy 
Can you provider the full url? i can't access this short url in china

**Comment by eyal-lezmy** [comment]
Sure. Here it is: https://docs.google.com/a/genymobile.com/forms/d/1cJUizfXdE2ccuFgJyYdK2UamYw8zvBCNcSEwy6FjRQw/edit
