### ISSUE TITLE
Bug in genymotion player

### ISSUE THREAD

**Issue by jitendra3109** [Genymobile/genymotion-gradle-plugin#22]
The last couple of week I was not able to use personal development genymotion because of Genymotion player not working.
I am terrifying what is the problem.
In my virtual box run properly but does not show image of Genymotion player.
So could you help?
I am attaching snapshot which will more clear about the problem.
1. Here I got stuck.
![screenshot from 2017-03-14 11-21-40](https://cloud.githubusercontent.com/assets/10773353/23887923/d2076a52-08aa-11e7-8ccf-f81e0557cb30.png)
![screenshot from 2017-03-14 11-23-50](https://cloud.githubusercontent.com/assets/10773353/23887925/d20e425a-08aa-11e7-8537-13b5e4d7fde6.png)
![screenshot from 2017-03-14 11-25-01](https://cloud.githubusercontent.com/assets/10773353/23887926/d20e5628-08aa-11e7-8ab1-7d9c8d3c7f33.png)
![screenshot from 2017-03-14 11-38-38](https://cloud.githubusercontent.com/assets/10773353/23887924/d20e35a8-08aa-11e7-98ca-a98b9072eb93.png)

**Comment by eyal-lezmy** [comment]
Hi @jsroyal,

Your problem is not related to the Gradle plugin for Genymotion. Please contact [the support team](https://www.genymotion.com/contact/) to try to fix the issue.

I close the ticket as it is not relevant for this project.
