### ISSUE TITLE
Unable to launch genymotion emulator automatically via my project build.gradle file

### ISSUE THREAD

**Issue by pavanagarwal** [Genymobile/genymotion-gradle-plugin#5]
Hi Team,

I got a trial version of licensed/enterprise genymotion tool and wanted to see if it can launch the emulator automatically and run my instrumentation/android functional tests. Am not sure what am missing in my build.gradle file but i do not see the emulator being launched. Here is my build.gradle file and test command am trying on my project.

```
Build.Gradle:
buildscript {
    dependencies {
        ...
        classpath 'com.genymotion:plugin:1.0'
    }

    repositories() {
        mavenLocal();
        maven {
            ...
        }
        mavenCentral();
        flatDir {
            dirs 'libs'
        }
        jcenter()
    }
}

...
apply plugin: 'genymotion'

genymotion {
    config {
        genymotionPath "/Applications/Genymotion.app/Contents/MacOS/"
        taskLaunch "runTest"
    }
    devices {
        nexus7 {
            template "Google Nexus 7 - 4.4.4 - API 19 - 800x1280"
            productFlavors "emulatorMockIControl"
            deleteWhenFinish false
        }
    }
}

...
```

Command to run tests:
./gradlew spoonEmulatorMockIControlDebugAndroidTestSmall

Notes:
When i manually launch the emulator and run above command, all instrumentation tests execute as expected.

Any inputs on this issue are highly appreciated. This will help us in making a decision if we need to spend money in the licensed version of genymotion tool.

Thanks,
Pavan

**Comment by eyal-lezmy** [comment]
Are you sure "runTest" is the good injection point for the genymotion tasks?

You can try first to set taskLaunch to "spoonEmulatorMockIControlDebugAndroidTestSmall" to check if it works. 
Also, add --debug to your command line and "verbose true" to genymotion.config to get relevant logs to paste on the issue.

Another little detail, on Windows and Mac you don't need to specify genymotionPath if Genymotion is installed on the default path.

**Comment by pavanagarwal** [comment]
@eyal-lezmy : Thanks a ton. That did work. I had a follow up question as my tests failed because the emulator that was launched automatically always opens up in Vertical mode. 
1) Is there a way we can launch the emulator in landscape mode? I mean is there any device property that i can set up in build.gradle file?

**Comment by eyal-lezmy** [comment]
Nope, that's not possible today but it is a very good input. 
We plan to add it to gmtool, to the Gradle plugin and to the [Genymotion Java API](https://www.genymotion.com/#!/developers/java-api) in the future.
