### ISSUE TITLE
Emulators not automatically launched when using newer versions of the Android Gradle plugin

### ISSUE THREAD

**Issue by futtetennista** [Genymobile/genymotion-gradle-plugin#7]
Since (at least) version `1.3.1` of the Android Gradle plugin, there have been some renaming wrt test task. In particular, a task like `connectedAndroidTestFlavorBuildType` has become `connectedFlavorBuildTypeAndroidTest`. This change breaks the plugin, since it relies on the task having the [`connectedAndroidTest`](https://github.com/Genymobile/genymotion-gradle-plugin/blob/abd7448253d8219026b8d61077937e1d19ded4b4/plugin/src/main/groovy/com/genymotion/tools/AndroidPluginTools.groovy#L27) prefix in order to add the launch/finish tasks.

**Comment by eyal-lezmy** [comment]
Hi @stefanodacchille 

Thanks for sharing. 
Actually there is another problem related to the task definition order on the Android Gradle plugin. We will dig into this problem and fix it asap.

You can work around it by explicitly defining the tasks you want the injection done. The build type for `connectedAndroidTest` is `Debug`. 
If you have two flavors (`flavor1` and `flavor2`) you can add to your build.gradle file:

```
genymotion.config {
    taskLaunch = ["connectedFlavor1DebugAndroidTest", "connectedFlavor2DebugAndroidTest"]
}
```

Sorry for this, we will make sure it won't happen again in the future.

**Comment by eyal-lezmy** [comment]
This bug has been fixed and will be available on the next release.

I close this issue.
Thanks a lot for the feedback!
