### ISSUE TITLE
Not possible to list tasks on project without genymotion credentials

### ISSUE THREAD

**Issue by sveinungkb** [Genymobile/genymotion-gradle-plugin#8]
For a project with multiple contributors it's not realistic to expect everyone to have Genymotion or want to use genymotion as their debugging platform and rather use devices or plain emulator.

Currently, if you specify the genymotion gradle configuration it will fail during task creation since it can't login without credentials.
The genymotion tasks should not login until they're executed, both to avoid the unnecessary network delays and to allow other developers to use the rest of the project.

**Comment by eyal-lezmy** [comment]
Hi @sveinungkb,

You can avoid this problem by setting the `abortOnError` config property to false. like this: 

```
genymotion.config {
    abortOnError false
}
```

This will make the Gradle plugin fro Genymotion will never fail the build.

**Comment by sveinungkb** [comment]
Thanks @eyal-lezmy , closing my issue.
