### ISSUE TITLE
How can I start/stop the emulator only once in a multi-library project?

### ISSUE THREAD

**Issue by sleekweasel** [Genymobile/genymotion-gradle-plugin#9]
For my multi-library Gradle-based Android project, each sub-project has tests, I'm trying to get the emulator to start before all tests and stop after all tests.

It's easy enough to get it to start and stop around each set of tests (by adding it to each library), but to make it start and stop once for the entire build, all I seem to be able to do is add a 'genymotionLaunch' and 'genymotionFinish' on either side of my command-line targets and tell the top level build file about it.

I was fiddling for ages yesterday, expecting a 'connectedCheck' target to exist at the top level, trying to make it depend on 'genymotionLaunch/Finish', with all sub-projects' 'connectedCheck' targets between them, but "gradle.plugin.com.dorongold.plugins:task-tree:1.0.1" strongly suggested that Gradle somehow offers 'connectedCheck' to each submodule in turn, with no corresponding top-level target (and I was unable to create that task, because the top level project appears to be evaluated completely before subprojects are considered, so subprojects{} didn't give me access).

Is there a way to hook into some top-level 'connectedCheck' task, or is the additional targets route the most sensible?

Thanks.

**Comment by eyal-lezmy** [comment]
Hi,

Thanks for your interesting question.

First, start/stopping the Genymotion devices between the tests is highly advised to avoid side effects. But you can decide it is not a problem for you.
To improve your Genymotion processes you can first choose to avoid deleting the devices after the launch by adding `deleteWhenFinish false` on each device declaration. The device will be created once, then it will directly be launched by the plugin.
Also, you can choose to keep the devices started all the time by adding `stopWhenFinish false` on each device declaration. They will never be stopped by the plugin. I advise you to sometime close them to be sure the devices are running well.

You can achieve the precise thing you are explaining by following this: 
You first need to have a `build.gradle` file at the root directory of your project. It seems you have it, if not, you can create a root project containing all your subprojects. Use this root to launch the Genymotion tasks with all your tests. You need to :
- Apply the genymotion plugin into the root project
- Create a task depending on all the `connectedCheck` task
- Declare the genymotion devices you want to run
- Link the genymotion tasks to the newly created task

Here is what the root project's `build.gradle` can look like:

``` groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.genymotion:plugin:1.0'
    }
}
apply plugin: 'genymotion'

task genymotionConnectedCheck << { }

subprojects {
    afterEvaluate {
        rootProject.tasks.genymotionConnectedCheck.dependsOn tasks.connectedCheck
        tasks.connectedCheck.mustRunAfter rootProject.tasks.genymotionLaunch
    }
}

afterEvaluate {
    tasks.genymotionConnectedCheck.dependsOn tasks.genymotionLaunch
    tasks.genymotionConnectedCheck.finalizedBy tasks.genymotionFinish
}

genymotion {
    devices {
        // Your devices
        nexus5 {
            template "Google Nexus 5 - 4.4.4 - API 19 - 1080x1920"
        }
        "my nexus 7" {
            template "Google Nexus 7 - 4.1.1 - API 16 - 800x1280"
        }
    }
}
```

Then, simply launch this new custom task to start all your tests:

``` sh
./gradlew :genymotionConnectedCheck
```

Let us know if it solve your problem.

Cheers
Eyal

**Comment by sleekweasel** [comment]
Ah... I see. I wasn't far off with my solution, but I was trying to construct it the wrong way. My gradle-fu isn't as strong as yours. :)

I've ended up adding gmtool command-line steps to our TeamCity build instead, because it was easier, I'm afraid, but many thanks for this insight into gradle!

**Comment by eyal-lezmy** [comment]
I'm glad you found a way to solve your problem. The piece of code I gave you is working as is so you can merge it into your current project if you want to avoid your CI's customization.

Thanks again for your question, that's a good opportunity for us to measure how to improve the product.

I close the ticket as the problem is resolved.
Cheers
